/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./.storybook/**/*.{js,ts,jsx,tsx}", // Ensure all relevant files are included
  ],
  prefix: "",
  theme: {
    container: {
      center: true, // Use boolean true instead of string 'true'
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        Proxima: ["Proxima", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
       'ref': {
            'primary': {
              0: 'hsl(var(--ref-primary-0) / <alpha-value>)',
              10: 'hsl(var(--ref-primary-10) / <alpha-value>)',
              20: 'hsl(var(--ref-primary-20) / <alpha-value>)',
              30: 'hsl(var(--ref-primary-30) / <alpha-value>)',
              40: 'hsl(var(--ref-primary-40) / <alpha-value>)',
              50: 'hsl(var(--ref-primary-50) / <alpha-value>)',
              60: 'hsl(var(--ref-primary-60) / <alpha-value>)',
              70: 'hsl(var(--ref-primary-70) / <alpha-value>)',
              80: 'hsl(var(--ref-primary-80) / <alpha-value>)',
              90: 'hsl(var(--ref-primary-90) / <alpha-value>)',
              100: 'hsl(var(--ref-primary-100) / <alpha-value>)',
            },
            'secondary': {
              0: 'hsl(var(--ref-secondary-0) / <alpha-value>)',
              10: 'hsl(var(--ref-secondary-10) / <alpha-value>)',
              20: 'hsl(var(--ref-secondary-20) / <alpha-value>)',
              30: 'hsl(var(--ref-secondary-30) / <alpha-value>)',
              40: 'hsl(var(--ref-secondary-40) / <alpha-value>)',
              50: 'hsl(var(--ref-secondary-50) / <alpha-value>)',
              60: 'hsl(var(--ref-secondary-60) / <alpha-value>)',
              70: 'hsl(var(--ref-secondary-70) / <alpha-value>)',
              80: 'hsl(var(--ref-secondary-80) / <alpha-value>)',
              90: 'hsl(var(--ref-secondary-90) / <alpha-value>)',
              100: 'hsl(var(--ref-secondary-100) / <alpha-value>)',
            },
            'accent-a': {
              0: 'hsl(var(--ref-accent-a-0) / <alpha-value>)',
              10: 'hsl(var(--ref-accent-a-10) / <alpha-value>)',
              20: 'hsl(var(--ref-accent-a-20) / <alpha-value>)',
              30: 'hsl(var(--ref-accent-a-30) / <alpha-value>)',
              40: 'hsl(var(--ref-accent-a-40) / <alpha-value>)',
              50: 'hsl(var(--ref-accent-a-50) / <alpha-value>)',
              60: 'hsl(var(--ref-accent-a-60) / <alpha-value>)',
              70: 'hsl(var(--ref-accent-a-70) / <alpha-value>)',
              80: 'hsl(var(--ref-accent-a-80) / <alpha-value>)',
              90: 'hsl(var(--ref-accent-a-90) / <alpha-value>)',
              100: 'hsl(var(--ref-accent-a-100) / <alpha-value>)',
            },
            'accent-b': {
              0: 'hsl(var(--ref-accent-b-0) / <alpha-value>)',
              10: 'hsl(var(--ref-accent-b-10) / <alpha-value>)',
              20: 'hsl(var(--ref-accent-b-20) / <alpha-value>)',
              30: 'hsl(var(--ref-accent-b-30) / <alpha-value>)',
              40: 'hsl(var(--ref-accent-b-40) / <alpha-value>)',
              50: 'hsl(var(--ref-accent-b-50) / <alpha-value>)',
              60: 'hsl(var(--ref-accent-b-60) / <alpha-value>)',
              70: 'hsl(var(--ref-accent-b-70) / <alpha-value>)',
              80: 'hsl(var(--ref-accent-b-80) / <alpha-value>)',
              90: 'hsl(var(--ref-accent-b-90) / <alpha-value>)',
              100: 'hsl(var(--ref-accent-b-100) / <alpha-value>)',
            },
            'accent-c': {
              0: 'hsl(var(--ref-accent-c-0) / <alpha-value>)',
              10: 'hsl(var(--ref-accent-c-10) / <alpha-value>)',
              20: 'hsl(var(--ref-accent-c-20) / <alpha-value>)',
              30: 'hsl(var(--ref-accent-c-30) / <alpha-value>)',
              40: 'hsl(var(--ref-accent-c-40) / <alpha-value>)',
              50: 'hsl(var(--ref-accent-c-50) / <alpha-value>)',
              60: 'hsl(var(--ref-accent-c-60) / <alpha-value>)',
              70: 'hsl(var(--ref-accent-c-70) / <alpha-value>)',
              80: 'hsl(var(--ref-accent-c-80) / <alpha-value>)',
              90: 'hsl(var(--ref-accent-c-90) / <alpha-value>)',
              100: 'hsl(var(--ref-accent-c-100) / <alpha-value>)',
            },
            'neutral': {
              0: 'hsl(var(--ref-neutral-0) / <alpha-value>)',
              10: 'hsl(var(--ref-neutral-10) / <alpha-value>)',
              20: 'hsl(var(--ref-neutral-20) / <alpha-value>)',
              30: 'hsl(var(--ref-neutral-30) / <alpha-value>)',
              40: 'hsl(var(--ref-neutral-40) / <alpha-value>)',
              50: 'hsl(var(--ref-neutral-50) / <alpha-value>)',
              60: 'hsl(var(--ref-neutral-60) / <alpha-value>)',
              70: 'hsl(var(--ref-neutral-70) / <alpha-value>)',
              80: 'hsl(var(--ref-neutral-80) / <alpha-value>)',
              90: 'hsl(var(--ref-neutral-90) / <alpha-value>)',
              100: 'hsl(var(--ref-neutral-100) / <alpha-value>)',
            },
            'error': {
              0: 'hsl(var(--ref-error-0) / <alpha-value>)',
              10: 'hsl(var(--ref-error-10) / <alpha-value>)',
              20: 'hsl(var(--ref-error-20) / <alpha-value>)',
              30: 'hsl(var(--ref-error-30) / <alpha-value>)',
              40: 'hsl(var(--ref-error-40) / <alpha-value>)',
              50: 'hsl(var(--ref-error-50) / <alpha-value>)',
              60: 'hsl(var(--ref-error-60) / <alpha-value>)',
              70: 'hsl(var(--ref-error-70) / <alpha-value>)',
              80: 'hsl(var(--ref-error-80) / <alpha-value>)',
              90: 'hsl(var(--ref-error-90) / <alpha-value>)',
              100: 'hsl(var(--ref-error-100) / <alpha-value>)',
            },
            'success': {
              0: 'hsl(var(--ref-success-0) / <alpha-value>)',
              10: 'hsl(var(--ref-success-10) / <alpha-value>)',
              20: 'hsl(var(--ref-success-20) / <alpha-value>)',
              30: 'hsl(var(--ref-success-30) / <alpha-value>)',
              40: 'hsl(var(--ref-success-40) / <alpha-value>)',
              50: 'hsl(var(--ref-success-50) / <alpha-value>)',
              60: 'hsl(var(--ref-success-60) / <alpha-value>)',
              70: 'hsl(var(--ref-success-70) / <alpha-value>)',
              80: 'hsl(var(--ref-success-80) / <alpha-value>)',
              90: 'hsl(var(--ref-success-90) / <alpha-value>)',
              100: 'hsl(var(--ref-success-100) / <alpha-value>)',
            },
            'warning': {
              0: 'hsl(var(--ref-warning-0) / <alpha-value>)',
              10: 'hsl(var(--ref-warning-10) / <alpha-value>)',
              20: 'hsl(var(--ref-warning-20) / <alpha-value>)',
              30: 'hsl(var(--ref-warning-30) / <alpha-value>)',
              40: 'hsl(var(--ref-warning-40) / <alpha-value>)',
              50: 'hsl(var(--ref-warning-50) / <alpha-value>)',
              60: 'hsl(var(--ref-warning-60) / <alpha-value>)',
              70: 'hsl(var(--ref-warning-70) / <alpha-value>)',
              80: 'hsl(var(--ref-warning-80) / <alpha-value>)',
              90: 'hsl(var(--ref-warning-90) / <alpha-value>)',
              100: 'hsl(var(--ref-warning-100) / <alpha-value>)',
            },
            'information': {
              0: 'hsl(var(--ref-information-0) / <alpha-value>)',
              10: 'hsl(var(--ref-information-10) / <alpha-value>)',
              20: 'hsl(var(--ref-information-20) / <alpha-value>)',
              30: 'hsl(var(--ref-information-30) / <alpha-value>)',
              40: 'hsl(var(--ref-information-40) / <alpha-value>)',
              50: 'hsl(var(--ref-information-50) / <alpha-value>)',
              60: 'hsl(var(--ref-information-60) / <alpha-value>)',
              70: 'hsl(var(--ref-information-70) / <alpha-value>)',
              80: 'hsl(var(--ref-information-80) / <alpha-value>)',
              90: 'hsl(var(--ref-information-90) / <alpha-value>)',
              100: 'hsl(var(--ref-information-100) / <alpha-value>)',
            },
            'neutral-scrim': 'hsl(var(--ref-neutral-scrim) / <alpha-value>)',
            'neutral-sh': 'hsl(var(--ref-neutral-sh) / <alpha-value>)',
          },
          'sys': {
            'radio': 'hsl(var(--sys-radio) / <alpha-value>)',
            'form-default': 'hsl(var(--sys-form-default) / <alpha-value>)',
            'form-hover': 'hsl(var(--sys-form-hover) / <alpha-value>)',
            'form-disabled': 'hsl(var(--sys-form-disabled) / <alpha-value>)',
            'form-error': 'hsl(var(--sys-form-error) / <alpha-value>)',
            'form-success': 'hsl(var(--sys-form-success) / <alpha-value>)',
            'form-active': 'hsl(var(--sys-form-active) / <alpha-value>)',
            'divider-decorative': 'hsl(var(--sys-divider-decorative) / <alpha-value>)',
            'divider-default': 'hsl(var(--sys-divider-default) / <alpha-value>)',
            'success': 'hsl(var(--sys-success) / <alpha-value>)',
            'on-success': 'hsl(var(--sys-on-success) / <alpha-value>)',
            'success-container': 'hsl(var(--sys-success-container) / <alpha-value>)',
            'on-success-container': 'hsl(var(--sys-on-success-container) / <alpha-value>)',
            'warning': 'hsl(var(--sys-warning) / <alpha-value>)',
            'on-warning': 'hsl(var(--sys-on-warning) / <alpha-value>)',
            'warning-container': 'hsl(var(--sys-warning-container) / <alpha-value>)',
            'on-warning-container': 'hsl(var(--sys-on-warning-container) / <alpha-value>)',
            'error': 'hsl(var(--sys-error) / <alpha-value>)',
            'on-error': 'hsl(var(--sys-on-error) / <alpha-value>)',
            'error-container': 'hsl(var(--sys-error-container) / <alpha-value>)',
            'on-error-container': 'hsl(var(--sys-on-error-container) / <alpha-value>)',
            'information': 'hsl(var(--sys-information) / <alpha-value>)',
            'on-information': 'hsl(var(--sys-on-information) / <alpha-value>)',
            'information-container': 'hsl(var(--sys-information-container) / <alpha-value>)',
            'on-information-container': 'hsl(var(--sys-on-information-container) / <alpha-value>)',
            'on-information-container-variant': 'hsl(var(--sys-on-information-container-variant) / <alpha-value>)',
            'neutral': 'hsl(var(--sys-neutral) / <alpha-value>)',
            'on-neutral': 'hsl(var(--sys-on-neutral) / <alpha-value>)',
            'neutral-container': 'hsl(var(--sys-neutral-container) / <alpha-value>)',
            'on-neutral-container': 'hsl(var(--sys-on-neutral-container) / <alpha-value>)',
            'surface': 'hsl(var(--sys-surface) / <alpha-value>)',
            'surface-bright': 'hsl(var(--sys-surface-bright) / <alpha-value>)',
            'on-surface': 'hsl(var(--sys-on-surface) / <alpha-value>)',
            'on-surface-variant': 'hsl(var(--sys-on-surface-variant) / <alpha-value>)',
            'surface-container': 'hsl(var(--sys-surface-container) / <alpha-value>)',
            'on-surface-container': 'hsl(var(--sys-on-surface-container) / <alpha-value>)',
            'surface-container-bright': 'hsl(var(--sys-surface-container-bright) / <alpha-value>)',
            'inverse-surface': 'hsl(var(--sys-inverse-surface) / <alpha-value>)',
            'on-inverse-surface': 'hsl(var(--sys-on-inverse-surface) / <alpha-value>)',
            'inverse-surface-container': 'hsl(var(--sys-inverse-surface-container) / <alpha-value>)',
            'on-inverse-surface-container': 'hsl(var(--sys-on-inverse-surface-container) / <alpha-value>)',
            'scrim': 'hsl(var(--sys-scrim) / <alpha-value>)',
            'primary': 'hsl(var(--sys-primary) / <alpha-value>)',
            'on-primary': 'hsl(var(--sys-on-primary) / <alpha-value>)',
            'primary-container': 'hsl(var(--sys-primary-container) / <alpha-value>)',
            'on-primary-container': 'hsl(var(--sys-on-primary-container) / <alpha-value>)',
            'secondary': 'hsl(var(--sys-secondary) / <alpha-value>)',
            'secondary-pressed': 'hsl(var(--sys-secondary-pressed) / <alpha-value>)',
            'on-secondary': 'hsl(var(--sys-on-secondary) / <alpha-value>)',
            'on-secondary-inverse': 'hsl(var(--sys-on-secondary-inverse) / <alpha-value>)',
            'secondary-container': 'hsl(var(--sys-secondary-container) / <alpha-value>)',
            'secondary-text': 'hsl(var(--sys-secondary-text) / <alpha-value>)',
            'on-secondary-container': 'hsl(var(--sys-on-secondary-container) / <alpha-value>)',
            'on-secondary-container-inverse': 'hsl(var(--sys-on-secondary-container-inverse) / <alpha-value>)',
            'accent-a': 'hsl(var(--sys-accent-a) / <alpha-value>)',
            'on-accent-a': 'hsl(var(--sys-on-accent-a) / <alpha-value>)',
            'accent-a-container': 'hsl(var(--sys-accent-a-container) / <alpha-value>)',
            'on-accent-a-container': 'hsl(var(--sys-on-accent-a-container) / <alpha-value>)',
            'accent-b': 'hsl(var(--sys-accent-b) / <alpha-value>)',
            'on-accent-b': 'hsl(var(--sys-on-accent-b) / <alpha-value>)',
            'accent-b-container': 'hsl(var(--sys-accent-b-container) / <alpha-value>)',
            'on-accent-b-container': 'hsl(var(--sys-on-accent-b-container) / <alpha-value>)',
            'accent-c': 'hsl(var(--sys-accent-c) / <alpha-value>)',
            'on-accent-c': 'hsl(var(--sys-on-accent-c) / <alpha-value>)',
            'accent-c-container': 'hsl(var(--sys-accent-c-container) / <alpha-value>)',
            'on-accent-c-container': 'hsl(var(--sys-on-accent-c-container) / <alpha-value>)',
            'accent-c-border': 'hsl(var(--sys-accent-c-border) / <alpha-value>)',
            'accent-a-border': 'hsl(var(--sys-accent-a-border) / <alpha-value>)',
            'accent-b-border': 'hsl(var(--sys-accent-b-border) / <alpha-value>)',
            'foil': 'var(--sys-foil)',
            'foil-horizontal': 'var(--sys-foil-horizontal)',
            'foil-vertical': 'var(--sys-foil-vertical)',
            'sweep': 'var(--sys-sweep)',
            'none': 'var(--sys-none)',
          },
          
        error: {
          DEFAULT: "hsl(var(--error))",
          foreground: "hsl(var(--error-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },

        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },

        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
